name: Performance Test

on: [repository_dispatch, workflow_dispatch]

jobs:

  inst:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: perf-db-order-single
            total: 100000
          - command: perf-db-order-dual
            total: 100000
          - command: perf-db-order-ten
            total: 30000

    steps:
          
      - name: Checkout statstrade-core
        uses: actions/checkout@v3
        with:
          repository: statstrade-dev/statstrade-core
          path: statstrade-core
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Setup postgres
        run: docker run -d --rm --network host --name postgres -e "POSTGRES_DB=test-scratch2" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_PORT=5432" -e "POSTGRES_USER=postgres" ghcr.io/zcaudate/infra-db:main
        
      - name: Run Performance
        run: >
          docker run --rm --network host 
          -v $(pwd):$(pwd) 
          -w $(pwd)
          -e BENCH_BATCH=1000
          -e BENCH_TOTAL=${{ matrix.total }}
          ghcr.io/zcaudate/foundation-ci:main 
          bash -c 'cd statstrade-core && lein ${{ matrix.command }}'
